apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc }}
