apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-{{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ecommerce.fullname" . }}
    service: {{ .Values.serviceName }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "ecommerce.fullname" . }}
    service: {{ .Values.serviceName }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 3000
      protocol: TCP
      name: http
